CREATE PROCEDURE CREATE_RESTAURANT_TABLE()
LANGUAGE SQL
AS $$
DROP TABLE IF EXISTS restaurant;
CREATE TABLE restaurant(
id int generated by default as identity,
lon double precision not null,
lat double precision not null,
name varchar(100) not null,
rating double precision not null,
primary key(id)
);
$$;